name = "AffineScaler"
uuid = "75005516-5893-409d-9e89-87dc6c6330eb"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[deps]
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
StructEquality = "1, 2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
